######
# H2
#spring:
#  h2:
#    console:
#      enabled: true
#     path: /h2-console
# Datasource
#  datasource:
#    url: jdbc:h2:file:~/beroutessbd
#   username: user
#  password: user
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update

#jwt:
#  secret: 12345
 